version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 18

  build:
    commands:
        - echo Installing dependencies...
        - npm ci
        - npm install- export BUCKET=giant-brain-serverless-ap
        - aws cloudformation package --template-file cloudFormation.json --s3-bucket $BUCKET --s3-prefix codepipeline --output-template-file outputtemplate.yml

artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml