apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-api-deployment
  labels:
    app: gb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gb-api
  template:
    metadata:
      labels:
        app: gb-api
    spec:
      containers:
      - name: gb-api
        image: tshims/giant-brain:master-d20c660
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gb-api-service
spec:
  type: NodePort
  selector:
    app: gb-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: Opaque
data:
  docker-username: dHNoaW1z
  docker-password: VHNoMW00bmc0I0A=
  docker-email: a2Fzc2FtcHUudHNoaW1hbmdhQGdtYWlsLmNvbQ==
  docker-server: aHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEv
