apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-api-deployment
  labels:
    app: gb-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app: gb-api
  template:
    metadata:
      labels:
        app: gb-api
    spec:
      containers:
      - name: gb-api
        image: tshims/giant-brain:master-7b5dce3
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: gb-api-service
spec:
  type: NodePort
  selector:
    app: gb-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
